apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab25
  labels:
    app: frontend-lab25
spec:
  selector:
    matchLabels:
      app: frontend-lab25
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-lab25
    spec:
      containers:
        - name: frontend-lab25
          image: nalleyda/frontend-lab25
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
